version: '3.8'

services:
  job-summary-generator:
    build: .
    ports:
      - "8000:8000"
    environment:
      - APP_NAME=Job Summary Generator
      - DEBUG=False
      - HOST=0.0.0.0
      - PORT=8000
      - USE_LOCAL_MODEL=false
      - USE_LLAMA4=false
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
      - HUGGINGFACE_API_URL=https://api-inference.huggingface.co/models/microsoft/DialoGPT-medium
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
